### ISSUE TITLE
How to encourage adoption? 

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/open-source-metatags#1]
Encouraging OSMT compliance is the core issue. I can think of a few ways:
- Encouraging the use of an OSMT badge on people's GitHub repos README.mds, so that the community starts seeing it on GitHub and expecting it in the source code
- Making an OSMT compliant checker in the form of a Chrome // Firefox extension, which shows a little ribbon or flag when a website is compliant, allowing ease of feedback. 
- Scanning GitHub Pages repositories and opening issues for popular websites, asking them to be compliant. 

Ideas?

**Comment by RichardLitt** [comment]
Chrome extension beta: https://github.com/RichardLitt/osmt-extension

**Comment by LeoVerto** [comment]
How about a simple list of participating websites?

**Comment by RichardLitt** [comment]
Might be a good idea, initially.

**Comment by simonv3** [comment]
Was just going to come on here and propose what @LeoVerto proposed.

**Comment by RichardLitt** [comment]
Perhaps just a section in the Readme, for now? MVP.

**Comment by simonv3** [comment]
:+1:

**Comment by RichardLitt** [comment]
Add them in!

**Comment by RichardLitt** [comment]
> Encouraging the use of an OSMT badge on people's GitHub repos README.mds, so that the community starts seeing it on GitHub and expecting it in the source code

I think this should be done by word of mouth.

> Making an OSMT compliant checker in the form of a Chrome // Firefox extension, which shows a little ribbon or flag when a website is compliant, allowing ease of feedback.

This should be added to a related projects section. 

> Scanning GitHub Pages repositories and opening issues for popular websites, asking them to be compliant.

I'm not going to do this, because I feel that the growth should be organic, and because I don't like bothering people.

**Comment by RichardLitt** [comment]
Added related projects section. Closing.
