### ISSUE TITLE
How does this relate to the meta="copyright" tag?

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/open-source-metatags#17]
http://www.metatags.org/meta_name_copyright

I know it's not the same thing, but was just wondering how you saw these being related.

**Comment by RichardLitt** [comment]
Hadn't seen that one yet. Interesting!

**Comment by RichardLitt** [comment]
So, they're not related. `copyright` is another tag, and I'm not impressed by metatags.org. Rather, this is about the source - is it open, and if so, where.

**Comment by simonv3** [comment]
I too, am not impressed by metatags.org
