### ISSUE TITLE
Should we use etags to specify live commit?

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/open-source-metatags#19]
[Etags](https://en.wikipedia.org/wiki/HTTP_ETag) are part of the HTTP protocol, meant for pointing to a specific version of a resource. It seems natural, then, that we ought to use etags to point to a particular version of a repository which the live site reflects.

**Comment by dydx** [comment]
Would you propose this into the OSP with the cache validation aspect in mind, or just as a reference for which commit is live?

I could see it being similar to version query strings for assets, but I don't know of a relatively idiomatic or easy way to implement the caching part. I think keeping a meta tag that references the commit id is a solid idea, though.

**Comment by RichardLitt** [comment]
I think that caching is better done elsewhere, and due to dynamic websites having a cache ID in the head probably wouldn't help much for anyone. Commit IDs, though are not as dynamic, and I think that would be a smart idea.

**Comment by RichardLitt** [comment]
I'm not sure that etags are relevant to OSP. With that, and with bbb2ffe63776b6e9df8364bf2b9ad5031f1b86dc, which allows `os:commit`, I think we are good for now. Reopen as you see fit, anyone.
