### ISSUE TITLE
How is this different from DOAP

### ISSUE THREAD

**Issue by Ed-0x1b** [RichardLitt/open-source-metatags#21]
Couldn't an RDFa DOAP profile do this just as well? how is OS different?
https://github.com/edumbill/doap

**Comment by RichardLitt** [comment]
@Ed-0x1b: I hadn't heard of this before. Cool! Hypothetically, yes, it could. Doesn't mean it can't be applied in parallel. 

It is different in that it doesn't come from the RDF community, but is aimed at, made for, and to a large extent by front end designers. This doesn't mean it isn't compatible, just that I have a different background, as do the people who helped work on this with me. It's not about software projects, it's about websites.

**Comment by HughP** [comment]
@RichardLitt I had linked to the DCMI profile for applications in our work on the Endangered-languages software list... see the conversation around [patch-2](https://github.com/RichardLitt/endangered-languages/pull/61#issuecomment-74824126).  DOAP is referenced in the [DCMI Profile](http://dublincore.org/groups/tools/map.shtml). 

[I talk a very little bit more](https://github.com/HughP/endangered-languages/blob/master/Record-options.md) about DOAP being suitable for extending descriptions of software for records of software being pushed to OLAC.

**Comment by RichardLitt** [comment]
I don't think this is the right direction. I don't think an ontology is or pushing records anywhere else but the web page is really useful. I just want the resources to be available to users of a web page directly in their browser.
