### ISSUE TITLE
os:git should be renamed to os:repo

### ISSUE THREAD

**Issue by simonv3** [RichardLitt/open-source-metatags#5]
Because git isn't the only version control system.

**Comment by simonv3** [comment]
Then you could have another tag called os:repo-type, and it could be git

**Comment by RichardLitt** [comment]
Why not just `os:repository`?

**Comment by simonv3** [comment]
because repo is shorter? beyond that I don't have a good reason

**Comment by RichardLitt** [comment]
Maybe we can use both? Make an alias?

**Comment by simonv3** [comment]
That seems like a bad idea

**Comment by RichardLitt** [comment]
Agreed. I guess I feel people are likely to put `repository` by accident, but not `repo`.

**Comment by RichardLitt** [comment]
Closed in 75538a3a0edb95f41be9031a82e41070e3f7dd87
