### ISSUE TITLE
Clarification about what OS means

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/open-source-metatags#8]
Doesn't mean the entire site, just the front end is enough

**Comment by simonv3** [comment]
What if you also had a os:related-project tag?

**Comment by RichardLitt** [comment]
How far would that rabbit hole go?

**Comment by simonv3** [comment]
Is that a problem?

**Comment by RichardLitt** [comment]
Better phrasing: What is the use of related-project? What scope are you thinking?

**Comment by simonv3** [comment]
For example, the front page of [Mailpile](https://www.mailpile.is/) is [open source](https://github.com/mailpile/www.mailpile.is), but [the main project](https://github.com/mailpile/Mailpile) is also open source, and isn't stored in the same place as the website.

I think there's a use case for a content consumer to see "oh, this is an opensource website, where is the code" (follows os:repo), and then. "Neat, where is the actual project that this is related to?" (follows os:project). 

It depends on whether you want the os: property tag to be a descriptor of the open source project or to just point at the source of the website.

**Comment by RichardLitt** [comment]
I guess I was worrying that `os:project` might be too confusing, but you're right that not having it might be more so. I'm happy with implementing it.

**Comment by RichardLitt** [comment]
We should also have an `os:project_src` then, too, no?

**Comment by simonv3** [comment]
I dunno, new day, I'm less convinced

**Comment by RichardLitt** [comment]
Same. I think project is too vague and contrary to the central point of describing the document itself.

—

**Comment by simonv3** [comment]
So maybe it should just be a `source` metatag? I think it's the "open" that's throwing me off.

**Comment by RichardLitt** [comment]
`os` means exactly what it says - open source. If you can find the code for the website online, than it is open source. Right?

**Comment by simonv3** [comment]
just because it means that, does that mean that that's what people will
think?

**Comment by RichardLitt** [comment]
I define it in the doc. I think following `og` here is fine. It's also a smaller footprint.
